# Generated by Django 5.1.4 on 2024-12-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['firstname']},
        ),
    ]
