# Generated by Django 5.1.4 on 2024-12-29 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_client_groups_remove_client_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='expenses.client'),
        ),
    ]
