# Generated by Django 5.1.4 on 2024-12-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='solde_apres_transaction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
