# Generated by Django 5.1.4 on 2024-12-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_transaction_solde_apres_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='solde_apres_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
